### ISSUE TITLE
REQUIRED: Add Test Coverage, Code Quality, and Code Style checks

### ISSUE THREAD

**Issue by LondonJim** [LazySamir/Acebook-EagleWithTopHat#7]
https://codeclimate.com/
https://github.com/bbatsov/rubocop
https://github.com/colszowka/simplecov

**Comment by EsamAl-Dabagh** [comment]
Rubocop, simpleCov to be configured

**Comment by EsamAl-Dabagh** [comment]
https://codeclimate.com/ needs repo owner to provide access.
